# Generated by Django 3.1.7 on 2021-07-31 17:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=50, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('seo_title', models.CharField(blank=True, help_text='Если заполнено, то используется вместо заголовка в title', max_length=100, verbose_name='SEO заголовок')),
                ('seo_description', models.CharField(blank=True, help_text='Рекомендуемая длина мета описания = 160 символов.', max_length=200, null=True, verbose_name='SEO описание')),
                ('seo_keywords', models.CharField(blank=True, help_text='Укажите ключевые слова через запятую.', max_length=2500, null=True, verbose_name='SEO ключевые слова')),
                ('title', models.CharField(max_length=225)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
